### PR TITLE
properly handle empty inductives

### LINKED ISSUE #122: pempty/false/empty are rendered as axioms
https://leanprover-community.github.io/mathlib_docs/init/core.html#empty

### PR DESCRIPTION
**Pull request by robertylewis**
This might fix #122 . Not tested yet.

### CODE REVIEW

**Comment by robertylewis** [comment]
#deploy

**Comment by robertylewis** [comment]
I'm confused by the CI failure. This worked locally:
image

**Comment by robertylewis** [comment]
The PR build (same commit as the push build) seems to have made more progress. Maybe it was a glitch, or maybe we're just about hitting a memory cap. My guess from the push build log is that export.json was empty so maybe the Lean process got killed for taking too much memory?

**Comment by bryangingechen** [comment]
> The PR build (same commit as the push build) seems to have made more progress. Maybe it was a glitch, or maybe we're just about hitting a memory cap. My guess from the push build log is that export.json was empty so maybe the Lean process got killed for taking too much memory?

A few days ago I also ran into a failing build which then worked when I restarted it: https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/doc-gen.20is.20failing/near/228676699

**Comment by robertylewis** [comment]
https://leanprover-community.github.io/mathlib_docs_demo/init/core.html#false

**Pull request merged**
