### PR TITLE
Adjusted dark theme

### PR DESCRIPTION
**Pull request by eric-wieser**
This changes the toggle button to be hidden in the left sidebar, and adds a third "system" option.
The old behavior was to override the users choice whenever the system settings changes, but this is no longer necessary.

This also fixes the `sorried` colors in dark mode, to:

image

Finally, this tweaks some navbar styles so that its right-hand side isn't clipped on small screens, as the color scheme options now sit against that right edge.

### CODE REVIEW

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by gebner** [comment]
The color_scheme.js file seems to be missing,.

**Comment by eric-wieser** [comment]
#deploy

**Comment by gebner** [comment]
BTW, `#deploy` takes a bit longer these days since we need to run the documentation generation on our self-hosted runners now.

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by gebner** [comment]
#deploy

**Pull request merged**
