### PR TITLE
Try to use the builtin math token

### PR DESCRIPTION
**Pull request by eric-wieser**
Redo of #115 since CI doesn't run properly on forks.

### CODE REVIEW

**Comment by eric-wieser** [comment]
#deploy

**Comment by bryangingechen** [comment]
#deploy

**Comment by bryangingechen** [comment]
Unfortunately, there's quite a bit of breakage compared to the current (admittedly, extremely hairy) approach: https://leanprover-community.github.io/mathlib_docs_demo/latex.html

Screen Shot 2021-02-16 at 12 45 43 PM

Screen Shot 2021-02-16 at 12 46 02 PM

**Comment by bryangingechen** [comment]
I'm closing this for now, feel free to re-open if you manage to get this approach working though!

**Pull request closed without merging**
