### PR TITLE
Include the archive and counterexamples directories

### LINKED ISSUE #147: Generate docs for the archive
Mathlib has other subdirectories in addition to src, it would be nice if there was a configurable option to generate docs for some of these too and include them in the sidebar, perhaps on the same level as mathlib as `mathlib-archive`.

### PR DESCRIPTION
**Pull request by eric-wieser**
This takes advantage of the new toml files in https://github.com/leanprover-community/mathlib/pull/18388.

Fixes #147.

This also adjusts the search box and find page to show the project name next to the result.
There is some styling discussion on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/docs.20archive/near/326367916), but there seems to be no strong preference between the first option (implemented in this PR) and the third one in that thread.

### CODE REVIEW

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by eric-wieser** [comment]
#deploy

**Comment by fpvandoorn** [comment]
I'm not able to properly review this, but nothing looks crazy, and the output is amazing.

bors merge

**Pull request merged**
