### PR TITLE
Flashy background highlighting.

### PR DESCRIPTION
**Pull request by gebner**
Patrick doesn't like my color scheme though.

flashy_highlighting

### CODE REVIEW

**Comment by robertylewis** [comment]
I love it!

**Comment by gebner** [comment]
How about this?  I think this represents the spirit of Lean very well:

flashy4

**Comment by robertylewis** [comment]
What about a gradient based on the sidebar color (green for theorems, etc)? Or is that too matchy? I guess we have blue links for everything so it could clash.

I'm fine with the current one btw, Patrick and I must have different tastes.

**Comment by jcommelin** [comment]
I like the fact that there is highlighting. I'm too much of a barbarian to have an opinion on the details.

**Pull request merged**
